feat: Testing renaming strategy
Signed-off-by: Thor Anker Kvisgård Lange <tal@netic.dk>

diff --git a/docker-start b/docker-start
--- a/docker-start
+++ b/docker-start
@@ -17,30 +17,36 @@ else
         }
 fi
 
-#source /usr/lib/frr/frrcommon.sh
-#/usr/lib/frr/watchfrr $(daemon_list)
-
-echo "Starting frr..."
-/usr/lib/frr/frrinit.sh start
-
-echo "Starting loop..."
-while true
-do
-  ip route
-  ip -6 route show default
-  if ! ip -6 route show default | grep -q "proto bgp"; then
-    # Clear the BGP session softly to re-push the RIB to the kernel
-    log_warning_msg "Could not find default route clearing BGP sessions"
-    ip route
-    ip -6 route
-    /usr/bin/vtysh -c "clear ip bgp * soft out"
-    /usr/bin/vtysh -c "clear ipv6 bgp * soft out"
-
-    sleep 10
-    echo "Dumping route table after refresh"
-    ip route
-    ip -6 route
-  fi
-
-  sleep 60
+# Wait for udev to rename the device
+while [ ! -d /sys/class/net/mgmt0 ]; do
+  echo "Waiting for mgmt0 to be renamed by udev..."
+  sleep 1
 done
+
+source /usr/lib/frr/frrcommon.sh
+/usr/lib/frr/watchfrr $(daemon_list)
+
+#echo "Starting frr..."
+#/usr/lib/frr/frrinit.sh start
+
+#echo "Starting loop..."
+#while true
+#do
+#  ip route
+#  ip -6 route show default
+#  if ! ip -6 route show default | grep -q "proto bgp"; then
+#    # Clear the BGP session softly to re-push the RIB to the kernel
+#    log_warning_msg "Could not find default route clearing BGP sessions"
+#    ip route
+#    ip -6 route
+#    /usr/bin/vtysh -c "clear ip bgp * soft out"
+#    /usr/bin/vtysh -c "clear ipv6 bgp * soft out"
+#
+#    sleep 10
+#    echo "Dumping route table after refresh"
+#    ip route
+#    ip -6 route
+#  fi
+#
+#  sleep 60
+#done
